### ISSUE TITLE
Feature request: Set gradient direction

### ISSUE THREAD

**Issue by jyounus** [mergesort/Slope#1]
Hey there,

It would be great if the two existing gradient classes (Uniform and Percentage Gradient) would support setting the direction. With "direction" I mean either vertical or horizontal gradients (so a gradient going from x: 0 to x: 1 or y:0 to y:1). 

Technically this could also be used to further extend the functionality to add diagonal gradient support, as part of this enum, but I don't care about diagonal right now. :P 

What do you think of providing this functionality out-of-the-box?

Here's my request visualised: 
![](https://flyingmeat.com/acorn/docs/gradient_tool3.png)

**Comment by mergesort** [comment]
Hey @jyounus! I just realized I had never replied with plans on how to address this, but thanks to the help of @adamstener, #2 adds support for this feature. Let me know if it works for you, and if not, if there's something else that can be done.

Thanks a lot!

**Comment by jyounus** [comment]
GradientAngle, perfect. Thanks for this! :D
